services:
  agenthub-package-registry:
    build: .
    container_name: agenthub-package-registry
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      agenthub-shared-net:
        aliases:
          - agenthub.package-registry.internal

networks:
  agenthub-shared-net:
    external: true
    name: agenthub-shared-net
